//
//  CDTAAppConstants.h
//  CDTA
//
//  Created by CooCooTech on 10/2/13.
//  Copyright (c) 2013 CooCoo. All rights reserved.
//

#import <Foundation/Foundation.h>
#define NSLog if(1) NSLog
@interface CDTAAppConstants : NSObject

FOUNDATION_EXPORT float const TOOLBAR_HEIGHT;
FOUNDATION_EXPORT float const VIEW_PADDING;
FOUNDATION_EXPORT float const ALERT_TEXT_SIZE;
FOUNDATION_EXPORT float const CELL_HEIGHT_DEFAULT;
FOUNDATION_EXPORT float const CELL_HEIGHT_LARGE;
FOUNDATION_EXPORT float const SEARCHED_CELL_HEIGHT;
FOUNDATION_EXPORT float const CELL_TEXT_SIZE_SMALL;
FOUNDATION_EXPORT NSString *const MODE_TRANSIT;
FOUNDATION_EXPORT NSString *const MODE_WALKING;
FOUNDATION_EXPORT NSString *const REAL_TIME_ARRIVAL;
FOUNDATION_EXPORT NSString *const ALERT_ALL_ROUTES;
FOUNDATION_EXPORT NSString *const ALERT_NX_ROUTE;
FOUNDATION_EXPORT int const NX_ROUTE_ID;

// NSUserDefaults
FOUNDATION_EXPORT NSString *const KEY_ORIGIN_NAME;
FOUNDATION_EXPORT NSString *const KEY_ORIGIN_ID;
FOUNDATION_EXPORT NSString *const KEY_ORIGIN_LATITUDE;
FOUNDATION_EXPORT NSString *const KEY_ORIGIN_LONGITUDE;
FOUNDATION_EXPORT NSString *const KEY_DESTINATION_NAME;
FOUNDATION_EXPORT NSString *const KEY_DESTINATION_ID;
FOUNDATION_EXPORT NSString *const KEY_DESTINATION_LATITUDE;
FOUNDATION_EXPORT NSString *const KEY_DESTINATION_LONGITUDE;

@end
